// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authz.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IsAuthorizedReqRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthorizedReqRequest) Reset()         { *m = IsAuthorizedReqRequest{} }
func (m *IsAuthorizedReqRequest) String() string { return proto.CompactTextString(m) }
func (*IsAuthorizedReqRequest) ProtoMessage()    {}
func (*IsAuthorizedReqRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{0}
}

func (m *IsAuthorizedReqRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthorizedReqRequest.Unmarshal(m, b)
}
func (m *IsAuthorizedReqRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthorizedReqRequest.Marshal(b, m, deterministic)
}
func (m *IsAuthorizedReqRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthorizedReqRequest.Merge(m, src)
}
func (m *IsAuthorizedReqRequest) XXX_Size() int {
	return xxx_messageInfo_IsAuthorizedReqRequest.Size(m)
}
func (m *IsAuthorizedReqRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthorizedReqRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthorizedReqRequest proto.InternalMessageInfo

func (m *IsAuthorizedReqRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *IsAuthorizedReqRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *IsAuthorizedReqRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type IsAuthorizedReqResponse struct {
	IsAuthorized         bool     `protobuf:"varint,1,opt,name=is_authorized,json=isAuthorized,proto3" json:"is_authorized,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAuthorizedReqResponse) Reset()         { *m = IsAuthorizedReqResponse{} }
func (m *IsAuthorizedReqResponse) String() string { return proto.CompactTextString(m) }
func (*IsAuthorizedReqResponse) ProtoMessage()    {}
func (*IsAuthorizedReqResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{1}
}

func (m *IsAuthorizedReqResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAuthorizedReqResponse.Unmarshal(m, b)
}
func (m *IsAuthorizedReqResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAuthorizedReqResponse.Marshal(b, m, deterministic)
}
func (m *IsAuthorizedReqResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAuthorizedReqResponse.Merge(m, src)
}
func (m *IsAuthorizedReqResponse) XXX_Size() int {
	return xxx_messageInfo_IsAuthorizedReqResponse.Size(m)
}
func (m *IsAuthorizedReqResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAuthorizedReqResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAuthorizedReqResponse proto.InternalMessageInfo

func (m *IsAuthorizedReqResponse) GetIsAuthorized() bool {
	if m != nil {
		return m.IsAuthorized
	}
	return false
}

func (m *IsAuthorizedReqResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Action struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{2}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Action) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Action) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CreateActionRequest struct {
	Action               *Action  `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateActionRequest) Reset()         { *m = CreateActionRequest{} }
func (m *CreateActionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateActionRequest) ProtoMessage()    {}
func (*CreateActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{3}
}

func (m *CreateActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateActionRequest.Unmarshal(m, b)
}
func (m *CreateActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateActionRequest.Marshal(b, m, deterministic)
}
func (m *CreateActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateActionRequest.Merge(m, src)
}
func (m *CreateActionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateActionRequest.Size(m)
}
func (m *CreateActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateActionRequest proto.InternalMessageInfo

func (m *CreateActionRequest) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type CreateActionResponse struct {
	Res                  *Action  `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateActionResponse) Reset()         { *m = CreateActionResponse{} }
func (m *CreateActionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateActionResponse) ProtoMessage()    {}
func (*CreateActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{4}
}

func (m *CreateActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateActionResponse.Unmarshal(m, b)
}
func (m *CreateActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateActionResponse.Marshal(b, m, deterministic)
}
func (m *CreateActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateActionResponse.Merge(m, src)
}
func (m *CreateActionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateActionResponse.Size(m)
}
func (m *CreateActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateActionResponse proto.InternalMessageInfo

func (m *CreateActionResponse) GetRes() *Action {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *CreateActionResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeleteActionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteActionRequest) Reset()         { *m = DeleteActionRequest{} }
func (m *DeleteActionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteActionRequest) ProtoMessage()    {}
func (*DeleteActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{5}
}

func (m *DeleteActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteActionRequest.Unmarshal(m, b)
}
func (m *DeleteActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteActionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteActionRequest.Merge(m, src)
}
func (m *DeleteActionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteActionRequest.Size(m)
}
func (m *DeleteActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteActionRequest proto.InternalMessageInfo

func (m *DeleteActionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteActionResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteActionResponse) Reset()         { *m = DeleteActionResponse{} }
func (m *DeleteActionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteActionResponse) ProtoMessage()    {}
func (*DeleteActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{6}
}

func (m *DeleteActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteActionResponse.Unmarshal(m, b)
}
func (m *DeleteActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteActionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteActionResponse.Merge(m, src)
}
func (m *DeleteActionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteActionResponse.Size(m)
}
func (m *DeleteActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteActionResponse proto.InternalMessageInfo

func (m *DeleteActionResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type UpdateActionRequest struct {
	Action               *Action  `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateActionRequest) Reset()         { *m = UpdateActionRequest{} }
func (m *UpdateActionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateActionRequest) ProtoMessage()    {}
func (*UpdateActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{7}
}

func (m *UpdateActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateActionRequest.Unmarshal(m, b)
}
func (m *UpdateActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateActionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateActionRequest.Merge(m, src)
}
func (m *UpdateActionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateActionRequest.Size(m)
}
func (m *UpdateActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateActionRequest proto.InternalMessageInfo

func (m *UpdateActionRequest) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type UpdateActionResponse struct {
	Res                  *Action  `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateActionResponse) Reset()         { *m = UpdateActionResponse{} }
func (m *UpdateActionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateActionResponse) ProtoMessage()    {}
func (*UpdateActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{8}
}

func (m *UpdateActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateActionResponse.Unmarshal(m, b)
}
func (m *UpdateActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateActionResponse.Marshal(b, m, deterministic)
}
func (m *UpdateActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateActionResponse.Merge(m, src)
}
func (m *UpdateActionResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateActionResponse.Size(m)
}
func (m *UpdateActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateActionResponse proto.InternalMessageInfo

func (m *UpdateActionResponse) GetRes() *Action {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *UpdateActionResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ListActionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActionsRequest) Reset()         { *m = ListActionsRequest{} }
func (m *ListActionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListActionsRequest) ProtoMessage()    {}
func (*ListActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{9}
}

func (m *ListActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActionsRequest.Unmarshal(m, b)
}
func (m *ListActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActionsRequest.Marshal(b, m, deterministic)
}
func (m *ListActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActionsRequest.Merge(m, src)
}
func (m *ListActionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListActionsRequest.Size(m)
}
func (m *ListActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListActionsRequest proto.InternalMessageInfo

type ListActionsResponse struct {
	Res                  []*Action `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
	Err                  string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListActionsResponse) Reset()         { *m = ListActionsResponse{} }
func (m *ListActionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListActionsResponse) ProtoMessage()    {}
func (*ListActionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{10}
}

func (m *ListActionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActionsResponse.Unmarshal(m, b)
}
func (m *ListActionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActionsResponse.Marshal(b, m, deterministic)
}
func (m *ListActionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActionsResponse.Merge(m, src)
}
func (m *ListActionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListActionsResponse.Size(m)
}
func (m *ListActionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListActionsResponse proto.InternalMessageInfo

func (m *ListActionsResponse) GetRes() []*Action {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *ListActionsResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetActionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActionRequest) Reset()         { *m = GetActionRequest{} }
func (m *GetActionRequest) String() string { return proto.CompactTextString(m) }
func (*GetActionRequest) ProtoMessage()    {}
func (*GetActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{11}
}

func (m *GetActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionRequest.Unmarshal(m, b)
}
func (m *GetActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionRequest.Marshal(b, m, deterministic)
}
func (m *GetActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionRequest.Merge(m, src)
}
func (m *GetActionRequest) XXX_Size() int {
	return xxx_messageInfo_GetActionRequest.Size(m)
}
func (m *GetActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionRequest proto.InternalMessageInfo

func (m *GetActionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetActionResponse struct {
	Res                  *Action  `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActionResponse) Reset()         { *m = GetActionResponse{} }
func (m *GetActionResponse) String() string { return proto.CompactTextString(m) }
func (*GetActionResponse) ProtoMessage()    {}
func (*GetActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{12}
}

func (m *GetActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionResponse.Unmarshal(m, b)
}
func (m *GetActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionResponse.Marshal(b, m, deterministic)
}
func (m *GetActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionResponse.Merge(m, src)
}
func (m *GetActionResponse) XXX_Size() int {
	return xxx_messageInfo_GetActionResponse.Size(m)
}
func (m *GetActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionResponse proto.InternalMessageInfo

func (m *GetActionResponse) GetRes() *Action {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetActionResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Resource struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{13}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Resource) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CreateResourceRequest struct {
	Resource             *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateResourceRequest) Reset()         { *m = CreateResourceRequest{} }
func (m *CreateResourceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateResourceRequest) ProtoMessage()    {}
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{14}
}

func (m *CreateResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResourceRequest.Unmarshal(m, b)
}
func (m *CreateResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResourceRequest.Marshal(b, m, deterministic)
}
func (m *CreateResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResourceRequest.Merge(m, src)
}
func (m *CreateResourceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateResourceRequest.Size(m)
}
func (m *CreateResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResourceRequest proto.InternalMessageInfo

func (m *CreateResourceRequest) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type CreateResourceResponse struct {
	Res                  *Resource `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err                  string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateResourceResponse) Reset()         { *m = CreateResourceResponse{} }
func (m *CreateResourceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResourceResponse) ProtoMessage()    {}
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{15}
}

func (m *CreateResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResourceResponse.Unmarshal(m, b)
}
func (m *CreateResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResourceResponse.Marshal(b, m, deterministic)
}
func (m *CreateResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResourceResponse.Merge(m, src)
}
func (m *CreateResourceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResourceResponse.Size(m)
}
func (m *CreateResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResourceResponse proto.InternalMessageInfo

func (m *CreateResourceResponse) GetRes() *Resource {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *CreateResourceResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeleteResourceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResourceRequest) Reset()         { *m = DeleteResourceRequest{} }
func (m *DeleteResourceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteResourceRequest) ProtoMessage()    {}
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{16}
}

func (m *DeleteResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResourceRequest.Unmarshal(m, b)
}
func (m *DeleteResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResourceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResourceRequest.Merge(m, src)
}
func (m *DeleteResourceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteResourceRequest.Size(m)
}
func (m *DeleteResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResourceRequest proto.InternalMessageInfo

func (m *DeleteResourceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResourceResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResourceResponse) Reset()         { *m = DeleteResourceResponse{} }
func (m *DeleteResourceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResourceResponse) ProtoMessage()    {}
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{17}
}

func (m *DeleteResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResourceResponse.Unmarshal(m, b)
}
func (m *DeleteResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResourceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResourceResponse.Merge(m, src)
}
func (m *DeleteResourceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResourceResponse.Size(m)
}
func (m *DeleteResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResourceResponse proto.InternalMessageInfo

func (m *DeleteResourceResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type UpdateResourceRequest struct {
	Resource             *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateResourceRequest) Reset()         { *m = UpdateResourceRequest{} }
func (m *UpdateResourceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateResourceRequest) ProtoMessage()    {}
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{18}
}

func (m *UpdateResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResourceRequest.Unmarshal(m, b)
}
func (m *UpdateResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResourceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResourceRequest.Merge(m, src)
}
func (m *UpdateResourceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateResourceRequest.Size(m)
}
func (m *UpdateResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResourceRequest proto.InternalMessageInfo

func (m *UpdateResourceRequest) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type UpdateResourceResponse struct {
	Res                  *Resource `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err                  string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateResourceResponse) Reset()         { *m = UpdateResourceResponse{} }
func (m *UpdateResourceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResourceResponse) ProtoMessage()    {}
func (*UpdateResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{19}
}

func (m *UpdateResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResourceResponse.Unmarshal(m, b)
}
func (m *UpdateResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResourceResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResourceResponse.Merge(m, src)
}
func (m *UpdateResourceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResourceResponse.Size(m)
}
func (m *UpdateResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResourceResponse proto.InternalMessageInfo

func (m *UpdateResourceResponse) GetRes() *Resource {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *UpdateResourceResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ListResourcesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResourcesRequest) Reset()         { *m = ListResourcesRequest{} }
func (m *ListResourcesRequest) String() string { return proto.CompactTextString(m) }
func (*ListResourcesRequest) ProtoMessage()    {}
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{20}
}

func (m *ListResourcesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResourcesRequest.Unmarshal(m, b)
}
func (m *ListResourcesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResourcesRequest.Marshal(b, m, deterministic)
}
func (m *ListResourcesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResourcesRequest.Merge(m, src)
}
func (m *ListResourcesRequest) XXX_Size() int {
	return xxx_messageInfo_ListResourcesRequest.Size(m)
}
func (m *ListResourcesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResourcesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListResourcesRequest proto.InternalMessageInfo

type ListResourcesResponse struct {
	Res                  []*Resource `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
	Err                  string      `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResourcesResponse) Reset()         { *m = ListResourcesResponse{} }
func (m *ListResourcesResponse) String() string { return proto.CompactTextString(m) }
func (*ListResourcesResponse) ProtoMessage()    {}
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{21}
}

func (m *ListResourcesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResourcesResponse.Unmarshal(m, b)
}
func (m *ListResourcesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResourcesResponse.Marshal(b, m, deterministic)
}
func (m *ListResourcesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResourcesResponse.Merge(m, src)
}
func (m *ListResourcesResponse) XXX_Size() int {
	return xxx_messageInfo_ListResourcesResponse.Size(m)
}
func (m *ListResourcesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResourcesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResourcesResponse proto.InternalMessageInfo

func (m *ListResourcesResponse) GetRes() []*Resource {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *ListResourcesResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetResourceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourceRequest) Reset()         { *m = GetResourceRequest{} }
func (m *GetResourceRequest) String() string { return proto.CompactTextString(m) }
func (*GetResourceRequest) ProtoMessage()    {}
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{22}
}

func (m *GetResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourceRequest.Unmarshal(m, b)
}
func (m *GetResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourceRequest.Marshal(b, m, deterministic)
}
func (m *GetResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourceRequest.Merge(m, src)
}
func (m *GetResourceRequest) XXX_Size() int {
	return xxx_messageInfo_GetResourceRequest.Size(m)
}
func (m *GetResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourceRequest proto.InternalMessageInfo

func (m *GetResourceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResourceResponse struct {
	Res                  *Resource `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err                  string    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetResourceResponse) Reset()         { *m = GetResourceResponse{} }
func (m *GetResourceResponse) String() string { return proto.CompactTextString(m) }
func (*GetResourceResponse) ProtoMessage()    {}
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{23}
}

func (m *GetResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourceResponse.Unmarshal(m, b)
}
func (m *GetResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourceResponse.Marshal(b, m, deterministic)
}
func (m *GetResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourceResponse.Merge(m, src)
}
func (m *GetResourceResponse) XXX_Size() int {
	return xxx_messageInfo_GetResourceResponse.Size(m)
}
func (m *GetResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourceResponse proto.InternalMessageInfo

func (m *GetResourceResponse) GetRes() *Resource {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetResourceResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Role struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RolePermissions      []*RolePermission `protobuf:"bytes,3,rep,name=role_permissions,json=rolePermissions,proto3" json:"role_permissions,omitempty"`
	CreatedAt            string            `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string            `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{24}
}

func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetRolePermissions() []*RolePermission {
	if m != nil {
		return m.RolePermissions
	}
	return nil
}

func (m *Role) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Role) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type RolePermission struct {
	ID                   string    `protobuf:"bytes,1,opt,name=iD,proto3" json:"iD,omitempty"`
	Resource             *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action               *Action   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RolePermission) Reset()         { *m = RolePermission{} }
func (m *RolePermission) String() string { return proto.CompactTextString(m) }
func (*RolePermission) ProtoMessage()    {}
func (*RolePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{25}
}

func (m *RolePermission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePermission.Unmarshal(m, b)
}
func (m *RolePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePermission.Marshal(b, m, deterministic)
}
func (m *RolePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePermission.Merge(m, src)
}
func (m *RolePermission) XXX_Size() int {
	return xxx_messageInfo_RolePermission.Size(m)
}
func (m *RolePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePermission.DiscardUnknown(m)
}

var xxx_messageInfo_RolePermission proto.InternalMessageInfo

func (m *RolePermission) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RolePermission) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *RolePermission) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type GetRoleRequest struct {
	RoleId               string   `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleRequest) Reset()         { *m = GetRoleRequest{} }
func (m *GetRoleRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoleRequest) ProtoMessage()    {}
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{26}
}

func (m *GetRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleRequest.Unmarshal(m, b)
}
func (m *GetRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleRequest.Marshal(b, m, deterministic)
}
func (m *GetRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleRequest.Merge(m, src)
}
func (m *GetRoleRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoleRequest.Size(m)
}
func (m *GetRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleRequest proto.InternalMessageInfo

func (m *GetRoleRequest) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

type GetRoleResponse struct {
	Res                  *Role    `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleResponse) Reset()         { *m = GetRoleResponse{} }
func (m *GetRoleResponse) String() string { return proto.CompactTextString(m) }
func (*GetRoleResponse) ProtoMessage()    {}
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{27}
}

func (m *GetRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleResponse.Unmarshal(m, b)
}
func (m *GetRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleResponse.Marshal(b, m, deterministic)
}
func (m *GetRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleResponse.Merge(m, src)
}
func (m *GetRoleResponse) XXX_Size() int {
	return xxx_messageInfo_GetRoleResponse.Size(m)
}
func (m *GetRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleResponse proto.InternalMessageInfo

func (m *GetRoleResponse) GetRes() *Role {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetRoleResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ListRolesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRolesRequest) Reset()         { *m = ListRolesRequest{} }
func (m *ListRolesRequest) String() string { return proto.CompactTextString(m) }
func (*ListRolesRequest) ProtoMessage()    {}
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{28}
}

func (m *ListRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRolesRequest.Unmarshal(m, b)
}
func (m *ListRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRolesRequest.Marshal(b, m, deterministic)
}
func (m *ListRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRolesRequest.Merge(m, src)
}
func (m *ListRolesRequest) XXX_Size() int {
	return xxx_messageInfo_ListRolesRequest.Size(m)
}
func (m *ListRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRolesRequest proto.InternalMessageInfo

type ListRolesResponse struct {
	Items                []*Role  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRolesResponse) Reset()         { *m = ListRolesResponse{} }
func (m *ListRolesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRolesResponse) ProtoMessage()    {}
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{29}
}

func (m *ListRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRolesResponse.Unmarshal(m, b)
}
func (m *ListRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRolesResponse.Marshal(b, m, deterministic)
}
func (m *ListRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRolesResponse.Merge(m, src)
}
func (m *ListRolesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRolesResponse.Size(m)
}
func (m *ListRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRolesResponse proto.InternalMessageInfo

func (m *ListRolesResponse) GetItems() []*Role {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListRolesResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type UserRole struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId       string   `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	StoreId              string   `protobuf:"bytes,4,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{30}
}

func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (m *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(m, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRole) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

func (m *UserRole) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

type User struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string      `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	UserId               string      `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsActive             bool        `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Provider             string      `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	Avatar               string      `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	OrganizationId       string      `protobuf:"bytes,8,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserRoles            []*UserRole `protobuf:"bytes,9,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	CreatedAt            string      `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string      `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b30dada73a254d2, []int{31}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *User) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

func (m *User) GetUserRoles() []*UserRole {
	if m != nil {
		return m.UserRoles
	}
	return nil
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*IsAuthorizedReqRequest)(nil), "pb.IsAuthorizedReqRequest")
	proto.RegisterType((*IsAuthorizedReqResponse)(nil), "pb.IsAuthorizedReqResponse")
	proto.RegisterType((*Action)(nil), "pb.Action")
	proto.RegisterType((*CreateActionRequest)(nil), "pb.CreateActionRequest")
	proto.RegisterType((*CreateActionResponse)(nil), "pb.CreateActionResponse")
	proto.RegisterType((*DeleteActionRequest)(nil), "pb.DeleteActionRequest")
	proto.RegisterType((*DeleteActionResponse)(nil), "pb.DeleteActionResponse")
	proto.RegisterType((*UpdateActionRequest)(nil), "pb.UpdateActionRequest")
	proto.RegisterType((*UpdateActionResponse)(nil), "pb.UpdateActionResponse")
	proto.RegisterType((*ListActionsRequest)(nil), "pb.ListActionsRequest")
	proto.RegisterType((*ListActionsResponse)(nil), "pb.ListActionsResponse")
	proto.RegisterType((*GetActionRequest)(nil), "pb.GetActionRequest")
	proto.RegisterType((*GetActionResponse)(nil), "pb.GetActionResponse")
	proto.RegisterType((*Resource)(nil), "pb.Resource")
	proto.RegisterType((*CreateResourceRequest)(nil), "pb.CreateResourceRequest")
	proto.RegisterType((*CreateResourceResponse)(nil), "pb.CreateResourceResponse")
	proto.RegisterType((*DeleteResourceRequest)(nil), "pb.DeleteResourceRequest")
	proto.RegisterType((*DeleteResourceResponse)(nil), "pb.DeleteResourceResponse")
	proto.RegisterType((*UpdateResourceRequest)(nil), "pb.UpdateResourceRequest")
	proto.RegisterType((*UpdateResourceResponse)(nil), "pb.UpdateResourceResponse")
	proto.RegisterType((*ListResourcesRequest)(nil), "pb.ListResourcesRequest")
	proto.RegisterType((*ListResourcesResponse)(nil), "pb.ListResourcesResponse")
	proto.RegisterType((*GetResourceRequest)(nil), "pb.GetResourceRequest")
	proto.RegisterType((*GetResourceResponse)(nil), "pb.GetResourceResponse")
	proto.RegisterType((*Role)(nil), "pb.Role")
	proto.RegisterType((*RolePermission)(nil), "pb.RolePermission")
	proto.RegisterType((*GetRoleRequest)(nil), "pb.GetRoleRequest")
	proto.RegisterType((*GetRoleResponse)(nil), "pb.GetRoleResponse")
	proto.RegisterType((*ListRolesRequest)(nil), "pb.ListRolesRequest")
	proto.RegisterType((*ListRolesResponse)(nil), "pb.ListRolesResponse")
	proto.RegisterType((*UserRole)(nil), "pb.UserRole")
	proto.RegisterType((*User)(nil), "pb.User")
}

func init() { proto.RegisterFile("authz.proto", fileDescriptor_6b30dada73a254d2) }

var fileDescriptor_6b30dada73a254d2 = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0x56, 0x9b, 0x7e, 0xa4, 0xa7, 0x7b, 0xdb, 0xce, 0xfd, 0x58, 0xde, 0x0e, 0xd0, 0x14, 0x40,
	0x1b, 0x20, 0xed, 0x62, 0xdc, 0xb0, 0x0b, 0x84, 0xaa, 0x0d, 0xa6, 0x4e, 0x5c, 0x4c, 0x91, 0x26,
	0x71, 0x37, 0x65, 0x8d, 0x45, 0x2d, 0xa5, 0x75, 0x66, 0xbb, 0xbb, 0xe8, 0x6f, 0xe0, 0x7f, 0xf0,
	0x2f, 0x90, 0xf8, 0x67, 0xc8, 0x8e, 0x93, 0x26, 0x26, 0x2d, 0x55, 0x77, 0x97, 0xf3, 0xf8, 0x7c,
	0x3d, 0xe7, 0x3c, 0xb1, 0x0c, 0x4d, 0x7f, 0x21, 0xa6, 0xcb, 0xd3, 0x88, 0x51, 0x41, 0x51, 0x39,
	0xba, 0x77, 0xbf, 0xc1, 0x60, 0xcc, 0x47, 0x0b, 0x31, 0xa5, 0x8c, 0x2c, 0x71, 0xe0, 0xe1, 0x07,
	0x0f, 0x3f, 0x2c, 0x30, 0x17, 0x08, 0x41, 0x65, 0xc1, 0x31, 0x73, 0x4a, 0x47, 0xa5, 0x93, 0x86,
	0xa7, 0xbe, 0x25, 0x16, 0xf9, 0x62, 0xea, 0x94, 0x63, 0x4c, 0x7e, 0xa3, 0x01, 0xd4, 0x66, 0x58,
	0x4c, 0x69, 0xe0, 0x58, 0x0a, 0xd5, 0x96, 0x7b, 0x03, 0x07, 0x7f, 0x65, 0xe6, 0x11, 0x9d, 0x73,
	0x8c, 0x5e, 0xc2, 0x7f, 0x84, 0xdf, 0xf9, 0xe9, 0x99, 0xaa, 0x61, 0x7b, 0x7b, 0x24, 0xe3, 0x8f,
	0x3a, 0x60, 0x61, 0xc6, 0x74, 0x29, 0xf9, 0xe9, 0xfe, 0x28, 0x41, 0x6d, 0x34, 0x11, 0x84, 0xce,
	0x51, 0x0b, 0xca, 0x24, 0xd0, 0xad, 0x95, 0x49, 0x20, 0x1b, 0x9b, 0xfb, 0x33, 0x9c, 0x34, 0x26,
	0xbf, 0xd1, 0x11, 0x34, 0x03, 0xcc, 0x27, 0x8c, 0x44, 0x32, 0x44, 0x77, 0x97, 0x85, 0xd0, 0x73,
	0x80, 0x09, 0xc3, 0xbe, 0xc0, 0xc1, 0x9d, 0x2f, 0x9c, 0x8a, 0x72, 0x68, 0x68, 0x64, 0x24, 0xe4,
	0xf1, 0x22, 0x0a, 0x92, 0xe3, 0x6a, 0x7c, 0xac, 0x91, 0x91, 0x70, 0xcf, 0xa1, 0x7b, 0xa1, 0x7c,
	0xe3, 0x9e, 0x92, 0xb9, 0xb9, 0x50, 0xf3, 0x15, 0xa0, 0xda, 0x6b, 0x9e, 0xc1, 0x69, 0x74, 0x7f,
	0xaa, 0x5d, 0xf4, 0x89, 0xfb, 0x05, 0x7a, 0xf9, 0x50, 0x3d, 0x98, 0x67, 0x60, 0x31, 0xcc, 0x0b,
	0x02, 0x25, 0x5c, 0x30, 0x91, 0xd7, 0xd0, 0xbd, 0xc4, 0x21, 0x36, 0x5b, 0x30, 0xa6, 0xe3, 0x9e,
	0x40, 0x2f, 0xef, 0xa6, 0xcb, 0xe9, 0x84, 0xa5, 0x55, 0xc2, 0x73, 0xe8, 0xde, 0x2a, 0x82, 0x3b,
	0x71, 0xca, 0x87, 0xee, 0xc8, 0xa9, 0x07, 0xe8, 0x2b, 0xe1, 0x22, 0x76, 0xe2, 0xba, 0x03, 0xf7,
	0x33, 0x74, 0x73, 0xa8, 0x99, 0xdc, 0xda, 0x2e, 0xb9, 0x0b, 0x9d, 0x2b, 0x2c, 0x36, 0x4f, 0xeb,
	0x02, 0xf6, 0x33, 0x3e, 0x3b, 0xb2, 0x08, 0xc1, 0xf6, 0x30, 0xa7, 0x0b, 0x36, 0xc1, 0x5b, 0x89,
	0x35, 0x2f, 0x45, 0x6b, 0xb3, 0x14, 0x2b, 0xa6, 0x14, 0x47, 0xd0, 0x8f, 0xf5, 0x94, 0xd4, 0x4c,
	0xb8, 0x9d, 0x80, 0xcd, 0x34, 0xa4, 0x7b, 0xdf, 0x93, 0xbd, 0xa7, 0x6e, 0xe9, 0xa9, 0x7b, 0x0d,
	0x03, 0x33, 0x85, 0xa6, 0xfe, 0x22, 0x4b, 0x3d, 0x1f, 0xbe, 0x86, 0xfc, 0x31, 0xf4, 0x63, 0xbd,
	0x99, 0xed, 0x98, 0xa3, 0x7e, 0x0b, 0x03, 0xd3, 0x71, 0xad, 0x34, 0x47, 0xd0, 0x8f, 0xf5, 0xf5,
	0x24, 0x8e, 0x66, 0x8a, 0x9d, 0x39, 0x0e, 0xa0, 0x27, 0x05, 0x99, 0xb8, 0xa5, 0x42, 0x1d, 0x43,
	0xdf, 0xc0, 0xcd, 0x12, 0xd6, 0xb6, 0x25, 0x5e, 0x01, 0xba, 0xc2, 0xe2, 0x5f, 0x33, 0xbc, 0x82,
	0x6e, 0xce, 0x6b, 0x67, 0x46, 0x3f, 0x4b, 0x50, 0xf1, 0x68, 0xb8, 0x9d, 0x5e, 0x3f, 0x42, 0x87,
	0xd1, 0x10, 0xdf, 0x45, 0x98, 0xcd, 0x08, 0xe7, 0xf2, 0xa7, 0x74, 0x2c, 0x45, 0x0d, 0xa9, 0x5a,
	0x34, 0xc4, 0x37, 0xe9, 0x91, 0xd7, 0x66, 0x39, 0x9b, 0x3f, 0xf1, 0xe6, 0x9d, 0x43, 0x2b, 0x5f,
	0x40, 0xb5, 0x7c, 0x99, 0xb6, 0x7c, 0x99, 0xd3, 0x44, 0x79, 0x93, 0x26, 0x32, 0x57, 0x9b, 0xb5,
	0xf6, 0x6a, 0x7b, 0x03, 0x2d, 0x39, 0x62, 0x1a, 0xa6, 0x4b, 0x38, 0x80, 0xba, 0xa2, 0x9f, 0xce,
	0xa9, 0x26, 0xcd, 0x71, 0xe0, 0x7e, 0x82, 0x76, 0xea, 0xaa, 0x37, 0x31, 0xcc, 0x6e, 0xc2, 0x4e,
	0xa6, 0xb3, 0x6e, 0x0b, 0x08, 0x3a, 0x4a, 0x3f, 0x34, 0xc4, 0x99, 0xcb, 0x6f, 0x3f, 0x83, 0xa5,
	0x0b, 0xae, 0x12, 0x81, 0x67, 0x89, 0xa2, 0x56, 0x89, 0x63, 0xb8, 0x20, 0x35, 0x03, 0xfb, 0x96,
	0x63, 0xb6, 0xf5, 0x8e, 0x8f, 0xa1, 0x4d, 0xd9, 0x77, 0x7f, 0x4e, 0x96, 0xbe, 0x1c, 0x83, 0x24,
	0x1b, 0x5f, 0x4c, 0xad, 0x2c, 0x3c, 0x0e, 0xd0, 0xff, 0x60, 0x73, 0x41, 0x99, 0x1a, 0x47, 0xbc,
	0xcb, 0xba, 0xb2, 0xc7, 0x81, 0xfb, 0xab, 0x0c, 0x15, 0x59, 0x74, 0xab, 0x82, 0x3d, 0xa8, 0xe2,
	0x99, 0x4f, 0x42, 0x5d, 0x26, 0x36, 0xe4, 0xac, 0xe5, 0xe3, 0x63, 0x95, 0xbc, 0x26, 0xcd, 0x71,
	0x80, 0x0e, 0xa1, 0x21, 0x9f, 0x11, 0x13, 0x41, 0x1e, 0xb1, 0x12, 0x89, 0xed, 0xd9, 0x84, 0x8f,
	0x94, 0x8d, 0x86, 0x60, 0x47, 0x8c, 0x3e, 0x92, 0x00, 0x33, 0xa7, 0xa6, 0xc2, 0x52, 0x5b, 0x3e,
	0x59, 0xfc, 0x47, 0x5f, 0xf8, 0xcc, 0xa9, 0xc7, 0x09, 0x63, 0xab, 0x88, 0xb0, 0x5d, 0x48, 0xf8,
	0x1d, 0x80, 0x6a, 0x49, 0x2e, 0x9d, 0x3b, 0x8d, 0xd5, 0x2f, 0x9d, 0xcc, 0xd7, 0x6b, 0x2c, 0xf4,
	0x97, 0xa9, 0x75, 0xd8, 0xac, 0xf5, 0xa6, 0xa1, 0xf5, 0xb3, 0xdf, 0x25, 0xa8, 0xca, 0x57, 0xd1,
	0x12, 0x5d, 0x43, 0xdb, 0x78, 0x50, 0xa1, 0xa1, 0xac, 0x59, 0xfc, 0x7e, 0x1b, 0x1e, 0x16, 0x9e,
	0x69, 0xf1, 0x9c, 0x41, 0x5d, 0xcb, 0x14, 0xa9, 0xff, 0x35, 0x2f, 0xef, 0x61, 0x37, 0x87, 0xe9,
	0x98, 0x0f, 0xd0, 0x48, 0x55, 0x88, 0x7a, 0xd2, 0xc3, 0x14, 0xea, 0xb0, 0x6f, 0xa0, 0x71, 0xe4,
	0x7d, 0x4d, 0xbd, 0x37, 0xdf, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x62, 0x78, 0x35, 0x7e,
	0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthzClient is the client API for Authz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthzClient interface {
	IsAuthorizedReq(ctx context.Context, in *IsAuthorizedReqRequest, opts ...grpc.CallOption) (*IsAuthorizedReqResponse, error)
	GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error)
	ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
}

type authzClient struct {
	cc *grpc.ClientConn
}

func NewAuthzClient(cc *grpc.ClientConn) AuthzClient {
	return &authzClient{cc}
}

func (c *authzClient) IsAuthorizedReq(ctx context.Context, in *IsAuthorizedReqRequest, opts ...grpc.CallOption) (*IsAuthorizedReqResponse, error) {
	out := new(IsAuthorizedReqResponse)
	err := c.cc.Invoke(ctx, "/pb.Authz/IsAuthorizedReq", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzClient) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error) {
	out := new(GetRoleResponse)
	err := c.cc.Invoke(ctx, "/pb.Authz/GetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzClient) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, "/pb.Authz/ListRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthzServer is the server API for Authz service.
type AuthzServer interface {
	IsAuthorizedReq(context.Context, *IsAuthorizedReqRequest) (*IsAuthorizedReqResponse, error)
	GetRole(context.Context, *GetRoleRequest) (*GetRoleResponse, error)
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
}

// UnimplementedAuthzServer can be embedded to have forward compatible implementations.
type UnimplementedAuthzServer struct {
}

func (*UnimplementedAuthzServer) IsAuthorizedReq(ctx context.Context, req *IsAuthorizedReqRequest) (*IsAuthorizedReqResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAuthorizedReq not implemented")
}
func (*UnimplementedAuthzServer) GetRole(ctx context.Context, req *GetRoleRequest) (*GetRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRole not implemented")
}
func (*UnimplementedAuthzServer) ListRoles(ctx context.Context, req *ListRolesRequest) (*ListRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoles not implemented")
}

func RegisterAuthzServer(s *grpc.Server, srv AuthzServer) {
	s.RegisterService(&_Authz_serviceDesc, srv)
}

func _Authz_IsAuthorizedReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthorizedReqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServer).IsAuthorizedReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Authz/IsAuthorizedReq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServer).IsAuthorizedReq(ctx, req.(*IsAuthorizedReqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authz_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Authz/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServer).GetRole(ctx, req.(*GetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authz_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Authz/ListRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServer).ListRoles(ctx, req.(*ListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authz_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Authz",
	HandlerType: (*AuthzServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAuthorizedReq",
			Handler:    _Authz_IsAuthorizedReq_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _Authz_GetRole_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _Authz_ListRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authz.proto",
}
